extends: eslint-config-dmitmel/presets/node
env:
  browser: true
  node: true
parserOptions:
  sourceType: module

settings:
  node:
    allowModules:
      - ultimate-crosscode-typedefs

rules:
  func-names: off

  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport

  node/no-unsupported-features/node-builtins:
    - error
    - ignores:
        - fs.promises

overrides:
  - files: '**/*.ts'
    extends: eslint-config-dmitmel/presets/typescript-with-type-checking-addon
    rules:
      node/no-missing-import: off

  - files: 'src/**/*.ts'
    parserOptions:
      project: 'tsconfig.json'
