name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/checkout@v2

      - name: Download ultimate-crosscode-typedefs
        uses: actions/checkout@v2
        with:
          repository: dmitmel/ultimate-crosscode-typedefs
          path: ultimate-crosscode-typedefs

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get Yarn cache directory
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
          key: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/

      - name: Set up ultimate-crosscode-typedefs
        working-directory: ultimate-crosscode-typedefs
        run: |
          yarn install --frozen-lockfile --production
          yarn link

      - name: Install dependencies
        run: |
          yarn link ultimate-crosscode-typedefs
          yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
